### ISSUE TITLE
Is this project still active? can it be archived?

### ISSUE THREAD

**Issue by edwardhorsford** [AlistairHCowan/user.wifi#2]
How does this repo relate to #alphagov/govwifi ? is it old? can it be archived?

**Comment by afoldesi-gds** [comment]
Sure, go ahead. The prototype service was shut down and users were migrated over to GovWifi earlier this year.

**Comment by edwardhorsford** [comment]
I don't have rights to this project - do you?

**Comment by Davidslv** [comment]
Would be good to update the README saying it has been deprecated.

**Comment by afoldesi-gds** [comment]
We could just archive it. ;)

**Comment by philandstuff** [comment]
done 😄
